# Generated by Django 5.2.6 on 2025-09-09 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conductor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuidad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Origen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origen', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_referencia', models.CharField(max_length=10, unique=True)),
                ('producto_nombre', models.TextField()),
                ('marca', models.CharField(max_length=40)),
                ('precio_ponderado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('peso_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendedor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Asociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula_Asociado', models.CharField(max_length=12)),
                ('nombre_Asociado', models.TextField()),
                ('cuidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogistica.cuidad')),
                ('Zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogistica.zona')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_productos_pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogistica.origen')),
                ('producto_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogistica.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_productos_negados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_negada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogistica.origen')),
                ('producto_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogistica.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas_contabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_factura', models.DateField()),
                ('peso_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_importacion', models.TextField()),
                ('estado_orden', models.BooleanField()),
                ('fecha_procesamiento', models.DateTimeField(auto_now_add=True)),
                ('cedula_Asociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogistica.asociado')),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogistica.conductor')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogistica.origen')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apilogistica.vendedor')),
            ],
        ),
    ]
